server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hdbPilot?useSSL=false&serverTimezone=UTC
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.iss.hdbPilot.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
