# 自定义的应用属性，用于配置AWS S3
aws:
  s3:
    bucket-name: "hdb-pilot"
  region: "ap-southeast-1"  # 你的S3存储桶所在的区域
  credentials:
    access-key: "AKIA5DFOLTC7LLUDPLFW"
    secret-key: "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"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hdbPilot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Profiles 配置：指定默认激活的环境为 dev (开发环境)
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.iss.hdbPilot.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl