# 自定义的应用属性，用于配置AWS S3
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:hdb-pilot}
  region: ${AWS_REGION:ap-southeast-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}

server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hdbPilot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Profiles 配置：指定默认激活的环境为 dev (开发环境)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.iss.hdbPilot.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl