# 开发环境配置
# 复制此文件为 application-local.yml 并填入你的实际数据库密码

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hdbPilot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Zyz20022201045
    driver-class-name: com.mysql.cj.jdbc.Driver

# 开发环境日志配置
logging:
  level:
    com.iss.hdbPilot: DEBUG
    org.springframework.web: DEBUG 