spring:
  datasource:
    url: jdbc:mysql://mysql-hdbpilot:3306/hdbPilot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Zyz20022201045 
    driver-class-name: com.mysql.cj.jdbc.Driver