# 生产环境配置
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:hdb-pilot}
  region: ${AWS_REGION:ap-southeast-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}

server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://mysql-hdbpilot:3306/hdbPilot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.iss.hdbPilot.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 生产环境特定配置
logging:
  file:
    name: /logs/hdbpilot.log
  level:
    root: INFO
    com.iss.hdbPilot: INFO
    org.springframework: WARN
    org.apache.ibatis: WARN